apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: adityanair006/kub-storage:latest
          env:
            - name: STORY_FOLDER
              # value: "story" #normal env
              valueFrom:
                configMapKeyRef: #Env file
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # emptyDir: {}
          # hostPath:
          #   path: /my-data
          #   type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc
