apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  hostPath: #We are using persistent volume hostPath as demo. Though it behaves same as the normal volume hostPath.
    path: /tasks
    type: DirectoryOrCreate
